### PR TITLE
Update deps, including trio + support recent Python versions + fix Github workflow

### PR DESCRIPTION
**Pull request by mikenerone**
Just providing some help with keeping Slurry up to date. Most importantly, this updates for current trio (no code changes needed), but also another minor dep or two (I didn't touch the docs deps because I didn't want to mess with checking that). I also updated classifiers and the Github workflow to include Python 3.11 & 3.12, which also needed a small fix because it was hitting an error during installation of Poetry.

### CODE REVIEW

**Comment by mikenerone** [comment]
As an aside, I've really fallen in love with Slurry. Super useful and beautiful code. I'd like to keep helping out with it when I can.

**Comment by andersea** [comment]
Hi @mikenerone Thanks for this submission. I am glad you like the project. I have not had an opportunity to use it myself for a while, so I don't get around to updating it as much these days. I will try to take a look the patch over the weekend.

As an aside, I see more and more trio-like features entering vanilla async, I am wondering if trio will eventually become more and more of a niche research project than something you would use in production. Slurry did help me out a lot back in the day with eliminating annoying boilerplate code, so I do think the general idea behind it has a lot of merit.

**Comment by andersea** [comment]
Ok, just had a quick look. Looks simple enough. Comitted.

**Comment by mikenerone** [comment]
My bad, I don't know why I was thinking that Python 3.7 was still supported - ignore that bit. I do think support for 3.8+ should be maintained because 3.8 is still supported and common (in fact, due to unfortunate constraints, my own app needs to work with it).

**Pull request merged**
